=== giellalt/dict-smn-fin/dtd/smnfin.dtd
<!ELEMENT r ( lics, e+ ) >

<!ATTLIST r id CDATA #IMPLIED >
<!ATTLIST r xmlns:xhtml CDATA #FIXED "http://www.w3.org/1999/xhtml"
          xml:lang (smn) #REQUIRED >



<!ELEMENT lics ( lic, ref*, sourcenote* )  >
<!ATTLIST lics xml:space (default|preserve) 'preserve'
    xmlns:xhtml CDATA #FIXED "http://www.w3.org/1999/xhtml"
>

<!ELEMENT lic (#PCDATA|a)* >
<!ATTLIST lic xml:lang (en) #IMPLIED >

<!ELEMENT ref (#PCDATA|a|i)* >
<!ELEMENT sourcenote (#PCDATA|a)* >

<!ELEMENT a ( #PCDATA ) >

<!ELEMENT e ( lg, mg+, ig* ) >
<!ATTLIST e id CDATA #IMPLIED >
<!ATTLIST e mc CDATA #IMPLIED >
<!ATTLIST e src CDATA #IMPLIED >

<!ELEMENT l ( #PCDATA ) >
<!ATTLIST l nr ( Pl ) #IMPLIED >
<!ATTLIST l pos ( A | Abbr | Adp | Adv | CC | CS | Clt | Interj |
                  N | Num | Pcle | Phrase | Po | Pr | Pron | Qu | V | X )
		  #IMPLIED >
<!ATTLIST l spec ( NomAg ) #IMPLIED >
<!ATTLIST l sem_type ( Obj | Plc | Fem | Org | Mal | Txt ) #IMPLIED >
<!ATTLIST l type NMTOKEN #IMPLIED >
<!ATTLIST l t_type ( Phrase ) #IMPLIED >
<!ATTLIST l sg1 CDATA #IMPLIED >
<!ATTLIST l sg3 CDATA #IMPLIED >
<!ATTLIST l pl3 CDATA #IMPLIED >
<!ATTLIST l gen CDATA #IMPLIED >
<!ATTLIST l ill CDATA #IMPLIED >
<!ATTLIST l sg_gen CDATA #IMPLIED >
<!ATTLIST l sg_ill CDATA #IMPLIED >
<!ATTLIST l pl_gen CDATA #IMPLIED >
<!ATTLIST l pl_ill CDATA #IMPLIED >
<!ATTLIST l g_stem CDATA #IMPLIED >
<!ATTLIST l v_type CDATA #IMPLIED >
<!ATTLIST l attr CDATA #IMPLIED >
<!ATTLIST l status CDATA #IMPLIED >
<!ATTLIST l hid CDATA #IMPLIED >

<!ELEMENT lg ( l, stem*, analysis*, mini_paradigm*, algu? ) >
<!ELEMENT analysis (#PCDATA|wordform)* >
<!ATTLIST analysis ms CDATA #IMPLIED >
<!ELEMENT wordform (#PCDATA) >
<!ELEMENT mini_paradigm (analysis+) >

<!ELEMENT mg ( tg ) >
<!ATTLIST mg rest CDATA #IMPLIED >

<!ELEMENT syn ( #PCDATA ) >
<!ELEMENT syng ( syn+ ) >

<!-- Idiom phrases, faste uttrykk -->
<!ELEMENT ig ( i+, id?, it+)+ >
<!ELEMENT i (#PCDATA) >
<!ELEMENT id (#PCDATA) >
<!ELEMENT it (#PCDATA) >


<!-- tg translation group -->

<!ELEMENT t ( #PCDATA ) >
<!ATTLIST t nr ( Pl ) #IMPLIED >
<!ATTLIST t pos ( A | Abbr | Adp | Adv | CC | CS | Clt | Cp | Det | Interj |
                  N | Num | Pcle | Po | Pr | Pron | V | X
) #IMPLIED >
<!ATTLIST t t_type NMTOKEN #IMPLIED >
<!ATTLIST t type ( Prop ) #IMPLIED >
<!ATTLIST t tt_auto CDATA #IMPLIED >
<!ATTLIST t rest CDATA #IMPLIED >
<!ATTLIST t l_par CDATA #IMPLIED >
<!ATTLIST t href CDATA #IMPLIED >

<!ELEMENT tg ( re | syng | morph_expl | t | xg )* >
<!ATTLIST tg xml:lang NMTOKEN #FIXED "fin" >
<!ELEMENT re (#PCDATA) > <!-- Domain restriction: bot, phys, ... -->
<!ELEMENT morph_expl (#PCDATA) >

<!ELEMENT x ( #PCDATA ) >

<!ELEMENT xg ( x, xt ) >

<!ELEMENT xt ( #PCDATA ) >

=== giellalt/dict-smn-fin/src/Pr_smnfin.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet media="screen"              title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary_XXE.css"     type="text/css"?>
<?xml-stylesheet media="screen"              title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_XXE_alt.css" type="text/css" alternate="yes" ?>
<?xml-stylesheet media="print,tv,projection" title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary.css"         type="text/css"?>
<?xml-stylesheet media="print,tv,projection" title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_alt.css"     type="text/css" alternate="yes" ?>
<!DOCTYPE r PUBLIC "-//DivvunGiellatekno//DTD Dictionaries//Multilingual" "../dtd/smnfin.dtd">
<r id="smnfin" xml:lang="smn">
   <lics xml:space="preserve">
  <lic xml:lang="en">
This code is made available under a Creative Commons Attribution license
<a>http://creativecommons.org/licenses/by/3.0/no/deed.en</a>.

You are free to copy, distribute and adapt the work, as long as you always give
proper attribution using the attribution text below.

For the full license text, see the link above.
</lic>
<ref>Work by Marja-Liisa Olthuis and Taarna Valtonen, and by Giellatekno at UiT,
          and members of the language communities. Source code
          available at <a>https://victorio.uit.no/langtech/trunk/</a>.</ref><sourcenote>
     THIS TEXT IS THE ORIGINAL SOURCE CODE. This is NOT a fully styled and
     published dictionary. As such it can and
     will contain unfinished entries, unpublished entries, entries with
     objectionable translations, etc. If you find any errors or want to add more
     words, download the file, edit it, and send it back to
     <a>mailtofeedback@divvun.no</a> and <a>mailtogiellatekno@hum.uit.no</a>.
     Please also note that the entries are not necessarily sorted,
     or could be wrongly sorted.
     </sourcenote></lics>
   <e id="A_865">
      <lg>
         <l pos="Adp">miätá</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="Adp">pitkin</t>
            <t pos="Adp">yltympäriinsä</t>
			<t pos="Adp">päästä päähän</t>
         </tg>
      </mg>
   </e>
   <e id="Pcle_1">
      <lg>
         <l pos="Adp">alda</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="Adp">lähellä</t>
            <t pos="Adp">läheltä</t>
         </tg>
      </mg>
   </e>
    <e id="Pcle_2">
      <lg>
         <l pos="Adp">aldasáid</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="Pr">lähes</t>
         </tg>
      </mg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="Adp">lähettyville</t>
         </tg>
      </mg>
   </e>
</r>

=== giellalt/dict-smn-fin/src/CC_smnfin.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet media="screen"              title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary_XXE.css"     type="text/css"?>
<?xml-stylesheet media="screen"              title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_XXE_alt.css" type="text/css" alternate="yes" ?>
<?xml-stylesheet media="print,tv,projection" title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary.css"         type="text/css"?>
<?xml-stylesheet media="print,tv,projection" title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_alt.css"     type="text/css" alternate="yes" ?>
<!DOCTYPE r PUBLIC "-//DivvunGiellatekno//DTD Dictionaries//Multilingual" "../dtd/smnfin.dtd">
<r id="smnfin" xml:lang="smn">
   <lics xml:space="preserve">
  <lic xml:lang="en">
This code is made available under a Creative Commons Attribution license
<a>http://creativecommons.org/licenses/by/3.0/no/deed.en</a>.

You are free to copy, distribute and adapt the work, as long as you always give
proper attribution using the attribution text below.

For the full license text, see the link above.
</lic>
<ref>Work by Marja-Liisa Olthuis and Taarna Valtonen, and by Giellatekno at UiT,
          and members of the language communities. Source code
          available at <a>https://victorio.uit.no/langtech/trunk/</a>.</ref><sourcenote>
     THIS TEXT IS THE ORIGINAL SOURCE CODE. This is NOT a fully styled and
     published dictionary. As such it can and
     will contain unfinished entries, unpublished entries, entries with
     objectionable translations, etc. If you find any errors or want to add more
     words, download the file, edit it, and send it back to
     <a>mailtofeedback@divvun.no</a> and <a>mailtogiellatekno@hum.uit.no</a>.
     Please also note that the entries are not necessarily sorted,
     or could be wrongly sorted.
     </sourcenote></lics>
   <e id="CC_1">
      <lg>
         <l pos="CC">adai</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="CC">eli</t>
            <t pos="CC">elikkä</t>
         </tg>
      </mg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="CC">tai</t>
         </tg>
      </mg>
   </e>
   <e id="CC_2">
      <lg>
         <l pos="CC">ađai</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="CC">eli</t>
            <t pos="CC">elikkä</t>
         </tg>
      </mg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="CC">tai</t>
         </tg>
      </mg>
   </e>
   <e id="CC_5">
      <lg>
         <l pos="CC">ege</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="CC">eikä</t>
         </tg>
      </mg>
   </e>
    <e id="CC_9">
      <lg>
         <l pos="CC">ige</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="CC">eikä</t>
         </tg>
      </mg>
   </e>
   <e id="CC_11">
      <lg>
         <l pos="CC">ja</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="CC">ja</t>
         </tg>
      </mg>
   </e>
   <e id="CC_12">
      <lg>
         <l pos="CC">já</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="CC">ja</t>
         </tg>
      </mg>
   </e>
   <e id="CC_13">
      <lg>
         <l pos="CC">jeđe</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="CC">ja niin</t>
         </tg>
      </mg>
   </e>
   <e id="CC_15">
      <lg>
         <l pos="CC">jite</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="CC">niin</t>
         </tg>
      </mg>
   </e>
   <e id="CC_18">
      <lg>
         <l pos="CC">mut</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="CC">mutta</t>
            <t pos="CC">vaan</t>
         </tg>
      </mg>
   </e>
    <e id="CC_18">
      <lg>
         <l pos="CC">mutâ</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="CC">mutta</t>
            <t pos="CC">vaan</t>
         </tg>
      </mg>
   </e>
   <e id="CC_20">
      <lg>
         <l pos="CC">pic</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="CC">mutta</t>
            <t pos="CC">vaan</t>
         </tg>
      </mg>
   </e>
   <e id="CC_20">
      <lg>
         <l pos="CC">peiccâ</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="CC">mutta</t>
            <t pos="CC">vaan</t>
         </tg>
      </mg>
   </e>
   <e id="CC_20">
      <lg>
         <l pos="CC">peic</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="CC">mutta</t>
            <t pos="CC">vaan</t>
         </tg>
      </mg>
   </e>
   <e id="CC_21">
      <lg>
         <l pos="CC">sehe</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="CC">sekä</t>
         </tg>
      </mg>
   </e>
   <e id="CC_21">
      <lg>
         <l pos="CC">sehe ... ete</l>
      </lg>
      <mg rest="- ete">
         <tg xml:lang="fin">
            <t pos="CC">sekä ... että</t>
         </tg>
      </mg>
   </e>
    <e id="CC_21">
      <lg>
         <l pos="CC">sehe ... et</l>
      </lg>
      <mg rest="- ete">
         <tg xml:lang="fin">
            <t pos="CC">sekä ... että</t>
         </tg>
      </mg>
   </e>
   <e id="CC_21">
      <lg>
         <l pos="CC">sehe ... já</l>
      </lg>
      <mg rest="- já">
         <tg xml:lang="fin">
            <t pos="CC">sekä ... että</t>
         </tg>
      </mg>
   </e>
   <e id="CC_24">
      <lg>
         <l pos="CC">tâi</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="CC">tai</t>
         </tg>
      </mg>
   </e>
   <e id="CC_25">
      <lg>
         <l pos="CC">taihe</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="CC">elikkä</t>
         </tg>
      </mg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="CC">eli</t>
         </tg>
      </mg>
   </e>
   <e id="CC_27">
      <lg>
         <l pos="CC">teikâ</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="CC">tai</t>
         </tg>
      </mg>
   </e>
   <e id="CC_28">
      <lg>
         <l pos="CC">teikkâ</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="CC">tai</t>
         </tg>
      </mg>
   </e>
   <e id="CC_29">
      <lg>
         <l pos="CC">váá</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="CC">vaan</t>
         </tg>
      </mg>
   </e>
   <e id="Pcle_10">
      <lg>
         <l pos="CC">eereeb</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="CC">paitsi</t>
         </tg>
      </mg>
   </e>
    <e id="Pcle_13">
      <lg>
         <l pos="CC">ereb</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="CC">paitsi</t>
         </tg>
      </mg>
   </e>
    <e id="Pcle_24">
      <lg>
         <l pos="CC">jo-uv ... teikkâ</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="CC">joko ... tai</t>
         </tg>
      </mg>
   </e>
    <e id="Pcle_24">
      <lg>
         <l pos="CC">jo-uv ... tâi</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="CC">joko ... tai</t>
         </tg>
      </mg>
   </e>
    <e id="Pcle_24">
      <lg>
         <l pos="CC">nuuvt ... ko</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="CC">niin ... kuin</t>
         </tg>
      </mg>
   </e>
    <e id="CC_29">
      <lg>
         <l pos="CC">ko váá</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="CC">kun(han) vain</t>
         </tg>
      </mg>
   </e>
    <e id="CC_29">
      <lg>
         <l pos="CC">ko peri</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="CC">kun(han) vain</t>
         </tg>
      </mg>
   </e>
    <e id="CS_14">
      <lg>
         <l pos="CC">te</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="CC">niin</t>
            <t pos="CC">sitten</t>
         </tg>
      </mg>
   </e>
    <e id="CS_14">
      <lg>
         <l pos="CC">jeđe</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="CC">ja niin</t>
            <t pos="CC">ja sitten</t>
         </tg>
      </mg>
   </e>
</r>

=== giellalt/dict-smn-fin/src/Der_smnfin.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet media="screen"              title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary_XXE.css"     type="text/css"?>
<?xml-stylesheet media="screen"              title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_XXE_alt.css" type="text/css" alternate="yes" ?>
<?xml-stylesheet media="print,tv,projection" title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary.css"         type="text/css"?>
<?xml-stylesheet media="print,tv,projection" title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_alt.css"     type="text/css" alternate="yes" ?>
<!DOCTYPE r
  PUBLIC "-//DivvunGiellatekno//DTD Dictionaries//Multilingual" "../dtd/smnfin.dtd">
<r id="smnfin" xml:lang="smn">
   <lics xmlns:xhtml="http://www.w3.org/1999/xhtml" xml:space="preserve"><lic xml:lang="en">
This code is made available under a Creative Commons Attribution license
<a>http://creativecommons.org/licenses/by/3.0/no/deed.en</a>.

You are free to copy, distribute and adapt the work, as long as you always give
proper attribution using the attribution text below.

For the full license text, see the link above.</lic>
      <ref>Work by Marja-Liisa Olthuis and Taarna Valtonen, and by Giellatekno at UiT,
          and members of the language communities. Source code
          available at <a>https://victorio.uit.no/langtech/trunk/</a>.</ref>
<sourcenote>
     THIS TEXT IS THE ORIGINAL SOURCE CODE. This is NOT a fully styled and
     published dictionary. As such it can and
     will contain unfinished entries, unpublished entries, entries with
     objectionable translations, etc. If you find any errors or want to add more
     words, download the file, edit it, and send it back to
     <a>mailto:feedback@divvun.no</a> and <a>mailto:giellatekno@uit.no</a>.
     Please also note that the entries are not necessarily sorted,
     or could be wrongly sorted.
     </sourcenote></lics>
   <e>
      <lg>
         <l pos="V">Der/InchL</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t t_type="grammarexpl"
	       href="http://oahpa.no/sme/gramm/suorggideapmi.nob.html#-goahtit">Lue
	    -kyettiđ-päätteestä (toistaiseksi vain pohjoissaamen –goahtit-päätteestä</t>
            <morph_expl>alkaa X</morph_expl>
         </tg>
      </mg>
   </e>
</r>

=== giellalt/dict-smn-fin/src/V_Negation_smnfin.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet media="screen"              title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary_XXE.css"     type="text/css"?>
<?xml-stylesheet media="screen"              title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_XXE_alt.css" type="text/css" alternate="yes" ?>
<?xml-stylesheet media="print,tv,projection" title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary.css"         type="text/css"?>
<?xml-stylesheet media="print,tv,projection" title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_alt.css"     type="text/css" alternate="yes" ?>
<!DOCTYPE r PUBLIC "-//DivvunGiellatekno//DTD Dictionaries//Multilingual" "../dtd/smnfin.dtd">
<r id="smnfin" xml:lang="smn">
   <lics xml:space="preserve">
  <lic xml:lang="en">
This code is made available under a Creative Commons Attribution license
<a>http://creativecommons.org/licenses/by/3.0/no/deed.en</a>.

You are free to copy, distribute and adapt the work, as long as you always give
proper attribution using the attribution text below.

For the full license text, see the link above.
</lic>
<ref>Work by Marja-Liisa Olthuis and Taarna Valtonen, and by Giellatekno at UiT,
          and members of the language communities. Source code
          available at <a>https://victorio.uit.no/langtech/trunk/</a>.</ref><sourcenote>
     THIS TEXT IS THE ORIGINAL SOURCE CODE. This is NOT a fully styled and
     published dictionary. As such it can and
     will contain unfinished entries, unpublished entries, entries with
     objectionable translations, etc. If you find any errors or want to add more
     words, download the file, edit it, and send it back to
     <a>mailtofeedback@divvun.no</a> and <a>mailtogiellatekno@hum.uit.no</a>.
     Please also note that the entries are not necessarily sorted,
     or could be wrongly sorted.
     </sourcenote></lics>
   <e id="V_1105">
      <lg>
         <l pos="V">jiem</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="V">en</t>
         </tg>
      </mg>
   </e>
   <e id="V_1101">
      <lg>
         <l pos="V" v_type="rv">jieh</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="V">et</t>
         </tg>
      </mg>
   </e>
    <e id="V_1101">
      <lg>
         <l pos="V" v_type="rv">ij</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="V">ei</t>
         </tg>
      </mg>
   </e>
   <e id="V_618">
      <lg>
         <l pos="V" v_type="rv">ep</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="V">emme (mon.)</t>
         </tg>
      </mg>
   </e>

   <e id="V_620">
      <lg>
         <l pos="V">eppeđ</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="V">ette (mon.)</t>
         </tg>
      </mg>
   </e>
   <e id="V_621">
      <lg>
         <l pos="V">eppee</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="V">ette (kaks.)</t>
         </tg>
      </mg>
   </e>
   <e id="V_1040">
      <lg>
         <l pos="V" v_type="rv">iä</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="V">eivät (mon.)</t>
         </tg>
      </mg>
   </e>
   <e id="V_1044">
      <lg>
         <l pos="V">iäge</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="V">eivätkä</t>
         </tg>
      </mg>
   </e>
   <e id="V_1053">
      <lg>
         <l pos="V" v_type="rv">iän</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="V">emme (kaks.)</t>
         </tg>
      </mg>
   </e>
   <e id="V_1071">
      <lg>
         <l pos="V" v_type="rv">iävá</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="V">eivät (duaali)</t>
         </tg>
      </mg>
   </e>

   <e id="V_604">
      <lg>
         <l pos="V" v_type="rv">ele</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="V">älä</t>
         </tg>
      </mg>
   </e>
   <e id="V_611">
      <lg>
         <l pos="V">elleđ</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="V">älkää (mon.)</t>
         </tg>
      </mg>
   </e>
   <e id="V_612">
      <lg>
         <l pos="V">ellee</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="V">älkää (kaks.)</t>
         </tg>
      </mg>
   </e>
</r>

=== giellalt/dict-smn-fin/src/Abbr_smnfin.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet media="screen"              title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary_XXE.css"     type="text/css"?>
<?xml-stylesheet media="screen"              title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_XXE_alt.css" type="text/css" alternate="yes" ?>
<?xml-stylesheet media="print,tv,projection" title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary.css"         type="text/css"?>
<?xml-stylesheet media="print,tv,projection" title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_alt.css"     type="text/css" alternate="yes" ?>
<!DOCTYPE r PUBLIC "-//DivvunGiellatekno//DTD Dictionaries//Multilingual" "../dtd/smnfin.dtd">
<r id="smnfin" xml:lang="smn">
   <lics xml:space="preserve">
  <lic xml:lang="en">
This code is made available under a Creative Commons Attribution license
<a>http://creativecommons.org/licenses/by/3.0/no/deed.en</a>.

You are free to copy, distribute and adapt the work, as long as you always give
proper attribution using the attribution text below.

For the full license text, see the link above.
</lic>
<ref>Work by Marja-Liisa Olthuis and Taarna Valtonen, and by Giellatekno at UiT,
          and members of the language communities. Source code
          available at <a>https://victorio.uit.no/langtech/trunk/</a>.</ref><sourcenote>
     THIS TEXT IS THE ORIGINAL SOURCE CODE. This is NOT a fully styled and
     published dictionary. As such it can and
     will contain unfinished entries, unpublished entries, entries with
     objectionable translations, etc. If you find any errors or want to add more
     words, download the file, edit it, and send it back to
     <a>mailtofeedback@divvun.no</a> and <a>mailtogiellatekno@hum.uit.no</a>.
     Please also note that the entries are not necessarily sorted,
     or could be wrongly sorted.
     </sourcenote></lics>
   <e id="Abbr_1">
      <lg>
         <l pos="Abbr">mkr</l>
      </lg>
      <mg rest="mannjeel kristus">
        <tg xml:lang="fin">
	  <re>jälkeen Kristuksen</re>
            <t pos="Abbr">jKr.</t>
         </tg>
      </mg>
   </e>
   <e id="A_1004">
      <lg>
         <l pos="Abbr">om.</l>
      </lg>
      <mg rest="ovdiibeln ma'inâšum">
         <tg xml:lang="fin">
            <t pos="Abbr">em. (edellä mainittu)</t>
         </tg>
      </mg>
   </e>
   <e id="N_10361">
      <lg>
         <l pos="N">stk</l>
      </lg>
      <mg rest="= stukkâ stuuhâ)">
         <tg xml:lang="fin">
            <t pos="N">kpl ( = kappale kappaletta)</t>
         </tg>
      </mg>
   </e>
   <e id="N_11291">
      <lg>
         <l g_stem="Sg" pos="Abbr" sg_gen="tme">tme</l>
      </lg>
      <mg rest="= tijme)">
         <tg xml:lang="fin">
            <t pos="Abbr">klo (= kello)</t>
         </tg>
      </mg>
   </e>
   <e id="N_11292">
      <lg>
         <l g_stem="Sg" pos="Abbr" sg_gen="tmt.">tmt.</l>
      </lg>
      <mg rest="tâi miinii tagarijd)">
         <tg xml:lang="fin">
            <t pos="Abbr">tms.</t>
            <t pos="Abbr">tai muuta sellaista</t>
         </tg>
      </mg>
   </e>
</r>
