=== giellalt/dict-smn-fin/scripts/dict_smnfin.dtd
<!ELEMENT r ( lics, e+ ) >

<!ATTLIST r id CDATA #IMPLIED >
<!ATTLIST r xmlns:xhtml CDATA #FIXED "http://www.w3.org/1999/xhtml"
          xml:lang (smn) #REQUIRED >



<!ELEMENT lics ( lic, ref*, sourcenote* )  >
<!ATTLIST lics xml:space (default|preserve) 'preserve' >

<!ELEMENT lic (#PCDATA|a)* >
<!ATTLIST lic xml:lang (en) #IMPLIED >

<!ELEMENT ref (#PCDATA|a|i)* >
<!ELEMENT sourcenote (#PCDATA|a)* >

<!ELEMENT a ( #PCDATA ) >
<!ELEMENT i ( #PCDATA ) >

<!ELEMENT e ( lg, mg+ ) >
<!ATTLIST e reverse NMTOKEN #IMPLIED >
<!ATTLIST e id CDATA #IMPLIED >
<!ATTLIST e mc CDATA #IMPLIED >
<!ATTLIST e src CDATA #IMPLIED >

<!ELEMENT l ( #PCDATA ) >
<!ATTLIST l comment CDATA #IMPLIED >
<!ATTLIST l nr ( Pl ) #IMPLIED >
<!ATTLIST l pos ( A | Abbr | Adp | Adv | CC | CS | Clt | Interj | 
                  N | Num | Pcle | Phrase | Po | Pr | Pron | Qu | V | X )
		  #REQUIRED >
<!ATTLIST l spec ( NomAg ) #IMPLIED >
<!ATTLIST l sem_type ( Obj | Plc | Fem | Org | Mal | Txt ) #IMPLIED >
<!ATTLIST l src NMTOKEN #IMPLIED >
<!ATTLIST l stem ( 2syll | 3syll | weak ) #IMPLIED >
<!ATTLIST l type NMTOKEN #IMPLIED >
<!ATTLIST l val ( IV | TV ) #IMPLIED >
<!ATTLIST l rest CDATA #IMPLIED >
<!ATTLIST l sg1 CDATA #IMPLIED >
<!ATTLIST l sg3 CDATA #IMPLIED >
<!ATTLIST l pl3 CDATA #IMPLIED >
<!ATTLIST l gen CDATA #IMPLIED >
<!ATTLIST l ill CDATA #IMPLIED >
<!ATTLIST l sg_gen CDATA #IMPLIED >
<!ATTLIST l sg_ill CDATA #IMPLIED >
<!ATTLIST l pl_gen CDATA #IMPLIED >
<!ATTLIST l pl_ill CDATA #IMPLIED >
<!ATTLIST l g_stem CDATA #IMPLIED >
<!ATTLIST l v_type CDATA #IMPLIED >
<!ATTLIST l attr CDATA #IMPLIED >
<!ATTLIST l status CDATA #IMPLIED >
<!ATTLIST l hid CDATA #IMPLIED >

<!ELEMENT lg ( l, stem*, analysis*, mini_paradigm*, algu? ) >
<!ELEMENT analysis (#PCDATA|wordform)* >
<!ATTLIST analysis ms CDATA #IMPLIED >
<!ELEMENT wordform (#PCDATA) >
<!ELEMENT mini_paradigm (analysis+) >

<!ELEMENT mg ( tg ) >
<!ATTLIST mg rest CDATA #IMPLIED >

<!ELEMENT syn ( #PCDATA ) >

<!ELEMENT syng ( syn+ ) >

<!ELEMENT t ( #PCDATA ) >
<!ATTLIST t comment CDATA #IMPLIED >
<!ATTLIST t nr ( Pl ) #IMPLIED >
<!ATTLIST t pos ( A | Abbr | Adp | Adv | CC | CS | Clt | Cp | Det | Interj | 
                  N | Num | Pcle | Phrase | Po | Pr | Pron | V | X 
) #REQUIRED >
<!ATTLIST t t_type NMTOKEN #IMPLIED >
<!ATTLIST t type ( Prop ) #IMPLIED >
<!ATTLIST t tt_auto CDATA #IMPLIED >
<!ATTLIST t re CDATA #IMPLIED >
<!ATTLIST t rest CDATA #IMPLIED >
<!ATTLIST t l_par CDATA #IMPLIED >

<!ELEMENT tg ( re | syng | t | xg )* >
<!ATTLIST tg comment CDATA #IMPLIED >
<!ATTLIST tg re CDATA #IMPLIED >
<!ATTLIST tg xml:lang ( fin ) #IMPLIED >
<!ELEMENT re (#PCDATA) > <!-- Domain restriction: bot, phys, ... -->

<!ELEMENT x ( #PCDATA ) >

<!ELEMENT xg ( x, xt ) >

<!ELEMENT xt ( #PCDATA ) >

=== giellalt/dict-smn-fin/src/Clitic_smnfin.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet media="screen"              title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary_XXE.css"     type="text/css"?>
<?xml-stylesheet media="screen"              title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_XXE_alt.css" type="text/css" alternate="yes" ?>
<?xml-stylesheet media="print,tv,projection" title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary.css"         type="text/css"?>
<?xml-stylesheet media="print,tv,projection" title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_alt.css"     type="text/css" alternate="yes" ?>
<!DOCTYPE r PUBLIC "-//DivvunGiellatekno//DTD Dictionaries//Multilingual" "../scripts/dict_smnfin.dtd">
<r id="smnfin" xml:lang="smn">
   <lics xml:space="preserve">
  <lic xml:lang="en">
This code is made available under a Creative Commons Attribution license
<a>http://creativecommons.org/licenses/by/3.0/no/deed.en</a>.

You are free to copy, distribute and adapt the work, as long as you always give
proper attribution using the attribution text below.

For the full license text, see the link above.
</lic>
<ref>Work by Marja-Liisa Olthuis and Taarna Valtonen, and by Giellatekno at UiT,
          and members of the language communities. Source code
          available at <a>https://victorio.uit.no/langtech/trunk/</a>.</ref><sourcenote>
     THIS TEXT IS THE ORIGINAL SOURCE CODE. This is NOT a fully styled and
     published dictionary. As such it can and
     will contain unfinished entries, unpublished entries, entries with
     objectionable translations, etc. If you find any errors or want to add more
     words, download the file, edit it, and send it back to
     <a>mailtofeedback@divvun.no</a> and <a>mailtogiellatekno@hum.uit.no</a>.
     Please also note that the entries are not necessarily sorted,
     or could be wrongly sorted.
     </sourcenote></lics>
   <e id="Clt_1">
      <lg>
         <l pos="Clt">râk</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="Clt">-pa ~ -pä</t>
         </tg>
      </mg>
   </e>
   <e id="CC_5">
      <lg>
         <l pos="Clt">-ge</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="Clt">-ka ~ -kä</t>
         </tg>
      </mg>
   </e>
  </r>

=== giellalt/dict-smn-fin/src/V_mwe_smnfin.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet media="screen"              title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary_XXE.css"     type="text/css"?>
<?xml-stylesheet media="screen"              title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_XXE_alt.css" type="text/css" alternate="yes" ?>
<?xml-stylesheet media="print,tv,projection" title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary.css"         type="text/css"?>
<?xml-stylesheet media="print,tv,projection" title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_alt.css"     type="text/css" alternate="yes" ?>
<!DOCTYPE r PUBLIC "-//DivvunGiellatekno//DTD Dictionaries//Multilingual" "../scripts/dict_smnfin.dtd">
<r id="smnfin" xml:lang="smn">
   <lics xml:space="preserve">
  <lic xml:lang="en">
This code is made available under a Creative Commons Attribution license
<a>http://creativecommons.org/licenses/by/3.0/no/deed.en</a>.

You are free to copy, distribute and adapt the work, as long as you always give
proper attribution using the attribution text below.

For the full license text, see the link above.
</lic>
<ref>Work by Marja-Liisa Olthuis and Taarna Valtonen, and by Giellatekno at UiT,
          and members of the language communities. Source code
          available at <a>https://victorio.uit.no/langtech/trunk/</a>.</ref><sourcenote>
     THIS TEXT IS THE ORIGINAL SOURCE CODE. This is NOT a fully styled and
     published dictionary. As such it can and
     will contain unfinished entries, unpublished entries, entries with
     objectionable translations, etc. If you find any errors or want to add more
     words, download the file, edit it, and send it back to
     <a>mailtofeedback@divvun.no</a> and <a>mailtogiellatekno@hum.uit.no</a>.
     Please also note that the entries are not necessarily sorted,
     or could be wrongly sorted.
     </sourcenote></lics>
   <e id="V_544">
      <lg>
         <l pos="V">leđe čuozân</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="V">olla sulkasadossa</t>
         </tg>
      </mg>
   </e>
   <e id="V_1731">
      <lg>
         <l pos="V">leđe kuástusist</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="V">häämöttää</t>
            <t pos="V">olla näkyvillä</t>
         </tg>
      </mg>
   </e>
   <e id="V_1758">
      <lg>
         <l pos="V">leđe kuhij</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="V">olla pitkässä hihnassa (koirasta)</t>
         </tg>
      </mg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="V">olla olla pidempi tai ulkonevampi kuin muut (esineistä)</t>
         </tg>
      </mg>
   </e>
   <e id="V_1866">
      <lg>
         <l pos="V">leđe kuuhij</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="V">olla pidempi tai ulkonevampi kuin muut (esineistä)</t>
         </tg>
      </mg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="V">olla pitkässä hihnassa (koirasta)</t>
         </tg>
      </mg>
   </e>
   <e id="V_4711">
      <lg>
         <l pos="V">tuápán moonnâđ</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="V">huopua</t>
         </tg>
      </mg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="V">kutistua (villavaatteesta)</t>
         </tg>
      </mg>
   </e>
   <e id="V_1731">
      <lg>
         <l pos="V">pieijâđ almosin</l>
      </lg>
      <mg rest="">
         <tg xml:lang="fin">
            <t pos="V">julkistaa</t>
         </tg>
      </mg>
   </e>
</r>
